[package]
name = "tay-cli"
version = "0.2.0"
authors = ["Mesut Tasci <mesut.tasci@trendyol.com>"]
edition = "2018"

[dependencies]
tay = {path = "../tay"}
rustyline = "10.0.0"


[[bin]]
name = "tay"
path = "src/main.rs"